spring.application.name=premium-calculator

# PostgreSQL (production)
spring.datasource.url=jdbc:postgresql://localhost:5432/life_premium
spring.datasource.username=life_user
spring.datasource.password=life_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect